name: Lint the docs

on:
  pull_request:
    paths:
      - '**.md'
      - '.markdownlint-cli2.jsonc'
      - '.github/workflows/lint-docs.yml'
  workflow_dispatch:

jobs:
  markdownlint:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Check the markdown
      run: npx --yes markdownlint-cli2 "**/*.md"
